import Head from 'next/head'
import './globals.css'
// import '@/styles/style.css'
// import { SessionProvider } from 'next-auth/react'
import type { AppProps } from 'next/app'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Music Player</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}


// export default function App({ Component, pageProps: { session, ...pageProps } }: AppProps) {
//   return (
//   <SessionProvider session={session}>
//    <Component {...pageProps} />
//   </SessionProvider>
//   )
// }
