import Head from 'next/head'
import './globals.css'
// import '@/styles/style.css'
// import { SessionProvider } from 'next-auth/react'
import type { AppProps } from 'next/app'
import SessionProvider from './SessionProvider'
import Header from '@/components/Header'
import Player from '@/components/Player'

export const metadata = {
  title: 'Cloud Player',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div className='flex flex-col min-h-screen mx-auto relative w-full lg:max-w-3xl bg-white'>
          <SessionProvider>
            <Header />
            {children}
            <Player />
          </SessionProvider>
        </div>
      </body>
    </html>
  )
}
